In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
# 1-d array
arr1 =np.array({1,2,3,4,5})

In [ ]:
arr1

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
# 2-d array
arr2=np.array([{1,2,3},{4,5,6}])
arr2

array([{1, 2, 3}, {4, 5, 6}], dtype=object)

In [ ]:
print(arr2.ndim)

1


In [ ]:
arr3=np.array([[[1,2,3,4],[5,6,7,8],[4,5,6,9]]])
arr3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [4, 5, 6, 9]]])

In [ ]:
# 0-d array
arr=np.array(44)
arr

array(44)

In [ ]:
arr3=np.zeros([2,3])
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones([3,3])
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# accessing array elements
arr2=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2[0,1]

2

In [ ]:
arr2[1,2]

6